### ISSUE TITLE
Normalizer error

### ISSUE THREAD

**Issue by jeffscottward** [AllAboutAI-YT/chatTTS#4]
INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
Here's a question:

If you could switch lives with someone for just one day, who would it be and why?
INFO:ChatTTS.core:All initialized.
WARNING:ChatTTS.core:Package nemo_text_processing not found!                         Run: conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing
Traceback (most recent call last):
  File "/Users/jeffscottward/Documents/GitHub/ChatTTS/ctts.py", line 35, in <module>
    wavs = chat.infer(texts, )
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffscottward/Documents/GitHub/ChatTTS/ChatTTS/core.py", line 146, in infer
    self.init_normalizer(_lang)
  File "/Users/jeffscottward/Documents/GitHub/ChatTTS/ChatTTS/core.py", line 199, in init_normalizer
    self.normalizer[lang] = partial(Normalizer(input_case='cased', lang=lang).normalize, verbose=False, punct_post_process=True)
                                    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'Normalizer' where it is not associated with a value

**Comment by luxingxiao** [comment]
I have the same problem
